### ISSUE TITLE
Want SDC/SmartOS platform consolidation

### ISSUE THREAD

**Issue by nshalman** [joyent/sdc-platform#3]
I'd like to use this issue to discuss my patches that allow an SDC Platform to behave like vanilla SmartOS and to eventually get something appropriate landed.

@sjorge has been kind enough to use my builds when testing LX brand features, so I have reason to believe that they generally work.

My builds are from my "downstream" branch: https://github.com/nshalman/sdc-platform/compare/downstream

The meat of the work is done in the first commit on that branch, and that is the one that needs the most scrutiny. It was recently fixed to remove a bug and to grab some fixes from smartos-live that in SDC currently live in headnode.sh.

The second commit brings in @rmustacc's WIP installer.

The third one adds some fixes to that installer and is intended to eventually be squashed down when the new installer is ready to ship.

Also, I think @jclulow may have been working on a similar project at some point, so I'll ping him too...

**Comment by rmustacc** [comment]
I'll try and take a longer look at this in the coming days.  I recall that there were various bugs in the wip installer, particularly around properly allowing the escaping out and detection of a zpool created thereof. Have their been subsequent changes to it to fix those errors?

**Comment by nshalman** [comment]
No, I haven't improved on the WIP installer at all. If there are known issues, perhaps that leans things in the direction of shipping the current installer rather than the WIP one for consolidation...

**Comment by sjorge** [comment]
+1, @nshalman chances work pretty well. There were some initial hickups but they seem to be gone in later images.

**Comment by nshalman** [comment]
I'll take a look at recreating and fixing the manual zpool creation issue.

**Comment by nshalman** [comment]
I narrowed down the issues I was seeing with zpool creation to the conditional creation of zones/usbkey that wasn't getting triggered when the script was run on a platform booted in noinstall mode (standalone=true,noimport=true).

I have been unable to recreate any other issues with zpool creation.

**Comment by nshalman** [comment]
I've started a wiki page to document the full plan for this work: http://wiki.smartos.org/display/DOC/Platform+Consolidation

**Comment by nshalman** [comment]
This was completed ages ago. Closing.
